const baseRequest = {
  models: ["stable_diffusion"],
  prompt: "",
  params: {
    steps: 30,
    post_processing: [],
    cfg_scale: 5,
    hires_fix: true,
    clip_skip: 1,
    width: 1024,
    image_is_control: false,
    height: 1024,
    tiling: false,
    karras: true,
    sampler_name: "k_dpmpp_sde",
    n: 1,
    denoising_strength: 0.75,
    facefixer_strength: 0.75,
    seed: "3103106036",
  },
  censor_nsfw: false,
  shared: true,
  replacement_filter: true,
  dry_run: false,
  r2: true,
  nsfw: true,
  trusted_workers: true,
  slow_workers: false,
};
exports.baseRequest = baseRequest;
