const baseRequest = {
  models: ["stable_diffusion"],
  prompt: "",
  params: {
    steps: 30,
    post_processing: [],
    cfg_scale: 7.5,
    hires_fix: false,
    clip_skip: 1,
    width: 512,
    image_is_control: false,
    height: 512,
    tiling: false,
    karras: false,
    sampler_name: "k_euler",
    n: 1,
    denoising_strength: 0.50,
    facefixer_strength: 0.50,
    seed: "3103106036",
  },
  censor_nsfw: true,
  shared: false,
  replacement_filter: true,
  dry_run: false,
  r2: true,
  nsfw: true,
  trusted_workers: true,
  slow_workers: false,
};
exports.baseRequest = baseRequest;
